### ISSUE TITLE
Can only change filetype now 

### ISSUE THREAD

**Issue by Drsexo** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#10]
Hello thank u for the update, i noticed in the new version we can only change the filetype theme and not the icons+toolbar anymore
is this intended ?
![7z](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/101467921/6d9b0fb3-6ab3-48b7-9ab2-b0bac5e4ad1b)

**Comment by Wilenty** [comment]
Hello,
yes there are some limitations in the latest v3.0 of 7zTC:
![any theme in one execution](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/5c211b98-3321-4a7a-8de6-4f429a90f99a)
but, when adding NanaZip.dll to 7-zip installation, only the file-type is available, because it's required.

Greetings,
Wilenty

**Comment by BinToss** [comment]
However, you can also choose the Toolbar theme with a workaround.
1. In "NanaZip FileType", press "Skip this file >"
    ![image](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/7243190/8f3f86bc-3f1b-4ed7-85e0-448976ff0b56)
3. In "NanaZip ToolBar", select your preferred toolbar theme.
    ![image](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/7243190/4ca3b22b-70db-4fee-9b10-80f21900463b)
5. Press "< Back"
6. Select your ToolBar theme.
    ![image](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/7243190/5bd04d00-ab8b-4608-8ebb-a24d84a1c214)
8. Press "Next >", then "Apply Theme(s)".
    ![image](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/7243190/cd56ac20-89c4-4e35-bb3c-e639fe51876e)
10. Wait for Setup to finish, then open NanaZip.
    ![image](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/7243190/d258fd44-dd1c-4d80-b024-25d05618deac)

**Comment by Wilenty** [comment]
Are you not cheeky to post a "workaround/crack" on my GitHub about my work?

You could have report this bug via separate issue, but you decided to post a "solution".

I had prepared next version of 7zTC 3.1 with zst.ico (without this bug), but I just waiting for 7-ZIP final version, if they will use it or not:
![7zTC-3_1](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/c212a0b2-3b76-4701-83bc-d5fc7043c398)

You are not allowed to write on my GH anymore, bye.

Greetings,
Wilenty

**Comment by Wilenty** [comment]
I wonder what would happen if @BinToss posted a "workaround" for the programs of larger companies on their forums, for example Adobe, Google, Microsoft?
