### ISSUE TITLE
Doesn't work with latest 7-Zip version

### ISSUE THREAD

**Issue by Franklin0770** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#14]
![2024-05-18 19_27_50-7-Zip Theme Changer v3 01](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/73434880/18a80fc5-1ba7-45aa-920a-ab499b351c5d)
As this screenshot tells, the program doesn't detect the latest version of 7-Zip (24.05) properly. Windows XP might be at fault here, but I'm not sure.

**Comment by Wilenty** [comment]
![01](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/fc3fc743-9ab4-4dc9-bba3-80d4806e756c)

![02](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/29f79154-3f0f-491c-af05-832e993ce7ec)

![03](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/00e56bbc-2e49-4a0d-a991-da95a76c8d2a)

![04](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/90dc8b7e-2adb-4151-a19c-ef0bddaa9a70)

P.S.
"Windows XP might be at fault here, but I'm not sure."
And I'm not sure if you are supporting the author of whom the works you are using?
