### ISSUE TITLE
Toolbar Theme not applying 24.05

### ISSUE THREAD

**Issue by SuperDOS** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#15]
7zip.dll is patched but not 7zFM.exe

**Comment by Wilenty** [comment]
Hello @SuperDOS.
Sorry but I can't reproduce your problem.

![01](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/84dc1bea-3729-4501-bf2c-d2a27b3516d4)

![02](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/5b69ec6d-aaf8-4f3b-9416-917f188fa6b3)

![03](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/02e45979-62e8-412a-9b44-2648dcd92d22)

![04](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/3f24596d-f160-4947-81cf-4f9be305ff9e)

Same for Windows XP "Doesn't work with latest 7-Zip version":
https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/issues/14#issuecomment-2118951843

The OS name and architecture is?
Please share the log-file, you see the save button at the end of installation - it was added in case of the problems.

Greetings,
Wilenty

**Comment by SuperDOS** [comment]
Ah sorry I had to click skip this file when running so the second time the toolbar theme got applied.
was a couple of years since last time I ran 7zTC :)
