### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by dahaut** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#16]
im trying to change toolbar and file icons on recently installed 7zip, but it doesnt seem to work. the process goes without errors and 7ztc says that it was successful but nothing actually changes
![image](https://github.com/user-attachments/assets/35c4a241-0eb4-48b8-8f0a-876fa7be3f2d)
![image](https://github.com/user-attachments/assets/0f96f207-0c4e-4f42-b636-7643a327ea0a)
![image](https://github.com/user-attachments/assets/e6482c1c-6db1-49a1-a182-dae34d86c6cf)
![image](https://github.com/user-attachments/assets/de16c74b-9500-460b-94c6-d09954e72d18)
[7zTC [Apply].txt](https://github.com/user-attachments/files/16481673/7zTC.Apply.txt)
![image](https://github.com/user-attachments/assets/6c45f952-524f-4f16-aff5-ca071b24b517)

**Comment by dahaut** [comment]
also for some reason it only lets me choose file type (as on the 2nd image) even when i also select toolbar and icons in some earlier menu

**Comment by Wilenty** [comment]
Hello @dahaut.

Firstly install 7-zip manually, and then use my program to change the theme(s) without installing 7-zip over and over again.

> also for some reason it only lets me choose file type (as on the 2nd image) even when i also select toolbar and icons in some earlier menu

![7zTC](https://github.com/user-attachments/assets/431da307-df7c-443d-a955-c7ed230e067a)

Greetings,
Wilenty

**Comment by dahaut** [comment]
@Wilenty thanks for your reply
for some reason now, after my pc spent some time turned off, file icons are indeed changed to what i selected. toolbar icons still arent though. i suppose it has something to do with
> also for some reason it only lets me choose file type (as on the 2nd image) even when i also select toolbar and icons in some earlier menu
but i dont know what to do about it

**Comment by Wilenty** [comment]
Dude you didn't read what I wrote before and you'll suggest me that you problem it's connected to something other than you do it wrong. 

Installing 7-ZIP:
![01 Installing7ZIP](https://github.com/user-attachments/assets/0f4ad9f3-04e2-43a4-94cd-191a0576dda7)
![02 Installed7ZIP](https://github.com/user-attachments/assets/1861c29b-1d6d-47b6-86d7-43bc75a5f7e3)

7-ZIP after installation:
![03 7zipAfterInstallation](https://github.com/user-attachments/assets/464c8ca5-ea05-499a-9137-d2cf5e546078)

7zTC main settings:
![04 7zTC](https://github.com/user-attachments/assets/06044c11-0cf7-4542-9bdb-1603422642c2)

7zTC FileType:
![05 FileType1](https://github.com/user-attachments/assets/705794ad-99b6-4ee4-9588-77a2e7fd28c6)
![05 FileType2](https://github.com/user-attachments/assets/c50cf85b-af16-4681-b30d-a4c6878fc955)

7zTC ToolBar:
![06 ToolBar1](https://github.com/user-attachments/assets/94cf57ba-98d7-4de8-83ae-5b1e0173926f)
![07 ToolBar2](https://github.com/user-attachments/assets/4538d280-aeed-4255-bfec-1b17caf3d553)

7zTC Icon:
![08 Icon1](https://github.com/user-attachments/assets/ab75a9b5-808e-4525-b467-c65192c22ad0)
![09 Icon2](https://github.com/user-attachments/assets/d323be1f-11e5-4dbc-821d-1f047f96d57b)

7-ZIP ater changes:
![10 7zipAterChanges](https://github.com/user-attachments/assets/e209f4ff-d83e-4afd-8fde-0bfdc038063e)

If I'm helping you to solve your problem - I'm expecting some financially help from you.

**Comment by dahaut** [comment]
dude i said it is working now. i dont have a problem with installation or anything, i just find it weird that while you can select filetype, toolbar and icons at the same time when selecting "launch 7ztc" you still need to launch it again and apply them individually later. thanks for your help though.

**Comment by ccrowles** [comment]
>while you can select filetype, toolbar and icons at the same time when selecting "launch 7ztc" you still need to launch it again and apply them individually later

I'm glad I found this issue thread because it cleared up what I wasn't understanding, dahaut's final message especially made it very clear that I had to relaunch it every time.

I wrongly assumed I would get prompted to change them one after the other and then click a """final""" apply, instead of opening it the first time, selecting the filetype theme, applying, closing, opening the second time, skipping, selecting the toolbar theme, applying, closing, opening the third time, skipping, skipping, selecting the icons theme, applying, closing.
(I wrote it in extensive detail for those that might also happen upon this thread as confused as I was.)

**Comment by Wilenty** [comment]
Hello @ccrowles.


Dahaut's messages are inaccurate (mutually exclusive).
In the screenshot of "Ready to Install" page he showing the main program from extracted/installed location:
![dahautSCREEN](https://github.com/user-attachments/assets/88e39b57-ff99-474e-a6cb-1f6e2c290fab)
but in the message he talking about Launching the main program from the Installer:
![dahautMSG](https://github.com/user-attachments/assets/660642b2-dc63-48b1-af18-8fde6c476078)

Let me show you what the path looks like when Executing main program from the Installer:
![7zTC-3_01](https://github.com/user-attachments/assets/c3b3b2b5-3b30-433d-93f8-4c1b14d6e41a)
![7zTC-3_01_0_2](https://github.com/user-attachments/assets/47cc1acc-10fa-4217-8b15-0b170891987a)
![3_01](https://github.com/user-attachments/assets/5ce9c18a-ce67-45d1-a1b2-d6383cdb5b6d)


I also wrongly assumed that people will help me financially by supporting my work, but it doesn't happen - they have only wishes: add this or that, change this or that, etc... So, I limited one theme per one execution. And in a short time I will add unskippable message to open my support page, if gently asking for support doesn't work.

Please use version 2.5 without any limitations (and without apfs.ico and NanaZip 3.0 support):
https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/releases/tag/v2.5
and please stop whining that you have to execute the program three times...


I consider this thread concluded.


Greetings,
Wilenty
