### ISSUE TITLE
[Feature improvements] Add Windows 10 Toolbar theme

### ISSUE THREAD

**Issue by Patrxgt** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#2]
It would be nice if you could add [this](https://www.deviantart.com/c3powen/art/Windows-10-7-Zip-toolbar-theme-602997424) toolbar theme to the preinstalled themes.

**Comment by Wilenty** [comment]
Hello,
I can do it, but I don't have the accounts everywhere, so please share the theme to add.

I see it in the first comment by "megapro17"
```
Here is installer with icons and toolbar. 7zTM can't mod 21.01 toolbar and i did it manually. no viruses i promise lol 

https://drive.google.com/drive/folders/1zKglz3x3jba1wWbkuCjHnIs_jQghfeFM
```
Which contains few themes:
7z2101-x64 Windows 10 Icons + Office 2013 Toolbar
&
7z2101-x64 Windows 10 Icons + Toolbar

If you can't share original theme, I can use the themes from first comment,  but the preview will be unavailable...

**Comment by Patrxgt** [comment]
Here I've packed few Windows 10 and Office 2013 themed toolbars, that your tool lacks:
[Windows 10 and Office toolbars.zip](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/files/8692992/Windows.10.and.Office.toolbars.zip)

Also, if you want more themes, then you can check out this GitHub repo: https://github.com/RipplePiam/7zip-Theme

**Comment by Wilenty** [comment]
Thank you for for sharing and the link for other themes - i added them all. :)

Added:
```
\---Filetype
   +---Windows 10 Blue
   +---Windows 10 Default
\---ToolBar
    +---Glyfz 2016
    +---Office 2013
    +---Windows 10 Blue
    +---Windows 10 Default
    +---Windows 10 Modern
```
And updated existing version: https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/releases/tag/v2.2.1

I want to provide a one-time special version of this program privately for you for your help, so please contact me at MDL or G3D.
MDL: https://forums.mydigitallife.net/members/wilenty.411805/
G3D: https://forums.guru3d.com/members/wilenty.273654/

BTW,
I don't think it's a "lack of themes", I adding them when users asking for it. If I wanted to add all available themes - the program probably will have size of one DVD... ;)

Probably I will create one opened "thread" here as a request to add users themes, so, here will be one "issue" for all request.

**Comment by Patrxgt** [comment]
Thank you for your work. 

> I want to provide a one-time special version of this program privately for you for your help, so please contact me at MDL or G3D. MDL: https://forums.mydigitallife.net/members/wilenty.411805/ G3D: https://forums.guru3d.com/members/wilenty.273654/

Sorry, but I don't use those platforms.
