### ISSUE TITLE
Doesn't work with NanaZip

### ISSUE THREAD

**Issue by Diego-VRFP** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#5]
I have tried it with 7-Zip and NanaZip and I have problems with NanaZip although according to the log everything is correct. I may be doing something wrong, I'm not an expert, but I wanted to record what's happening to me. I am using Windows 10 and have restarted the PC after each installation to make sure everything was fine.

When using it with Nanazip I have tried two methods.
The first one, I assign it the windowsapps path and it doesn't let me choose icons for the File Types, it only lets me change the Icons and the icons of the Toolbar, and when the installation is finished it makes the program not work and gives me a unknown error message when trying to open it.
With the second method I put the Nanazip installer to 7ztc. In this way, it does let me choose the icons of the File Types, but as with the other method, when the installation is finished, the program does not work and gives me an unknown error message when trying to open it.

With 7-Zip it works well for me, although to put a hitch it doesn't change the icon of the contextual menu.

**Comment by Wilenty** [comment]
Hello @Disdef

> I'm not an expert, but I wanted to record what's happening to me. I am using Windows 10 and have restarted the PC after each installation to make sure everything was fine.

No problem, you can always ask. :)



For problems with NanZip I have no idea, this program is written to work with Windows Store and it's Store App.
Last version of NanaZip I "tested" with 7zTC (v2.5) was v1.2.252.0 (40174MouriNaruto.NanaZip_1.2.252.0_gnj4mf6z9tkrc.msixbundle) when this version was created.
NanZip is constantly changing, and honestly I have no time to track all of the the changes of NanaZip and modify my program - sorry...
I even created a uninstaller for NanaZip, but the owner said: https://forums.mydigitallife.net/threads/nanazip-open-source-file-archiver-intended-for-the-modern-windows-experience.84171/page-4#post-1727409
> I need to do lots of work before release the .exe version.

and: https://forums.mydigitallife.net/threads/nanazip-open-source-file-archiver-intended-for-the-modern-windows-experience.84171/page-6#post-1763136
> There are some issues from the toolchain need to be solved before releasing a legacy installer style version.



For second mentioned problem with changing the icons in the Windows Explorer, please look at this thread: https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/issues/4#issuecomment-1367314016



Greetings,
Wilenty

![NanaZip-W10](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/e362d778-4ea6-4f10-85cb-ec6e7a6a93f8)

P.S.
But, if you need the support for more formats (codecs, etc.) in 7-zip, please look at this: https://github.com/Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script

**Comment by Wilenty** [comment]
Hello ten2120,
I was tested the option to patch NanaZip of Windows Store in W10 and early W11. But I don't recommend to "play with Windows Store", because you can have to reinstall or repair the Windows OS. Windows Store is protected by the OS, and I don't want break it, so, I don't have any better solution for this.

It's better to use latest version of 7zTC to install any version of NanaZip to "C:\Program Files" (or whatever else), or add NanaZip.dll to 7-Zip installation, then you will have all possible formats and codecs available in 7-Zip.

Greetings,
Wilenty

**Comment by Diego-VRFP** [comment]
Hello again. Yesterday I updated my PC to Win11 and yes, if I install the NanaZip 1.2 version in C: the theme change works, but when I do it this way Nanazip does not appear in the new Win11 context menu, if I click show more options does appear, but there I also got 7z and my idea was to install NanaZip so that it would appear in the main Context Menu. 
Is there a solution to that, or do only Windows applications appear in the main context menu?

**Comment by Wilenty** [comment]
Hello (again).

There are many pages on the internet "how to bring back full/old right-click menu".
I just paste two links from beginning of the search list:
https://www.xda-developers.com/how-to-open-full-right-click-menu-by-default-windows-11/
https://www.howtogeek.com/759559/how-to-find-missing-right-click-context-menu-options-on-windows-11/

Greetings,
Wilenty

BTW:
https://sourceforge.net/p/sevenzip/discussion/45797/thread/14f6621a45/
