### ISSUE TITLE
The icons return as before when changing the View to small icons!!

### ISSUE THREAD

**Issue by issam-seghir** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#7]
![explorer_RsoOG9hE5o](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/74573675/b672dd8c-d4af-42fe-a3ec-e7d5c85a5eeb)

**Comment by Wilenty** [comment]
Hello @Issam-seghir,
for first please look at the pinned topic: "Some Icons Don't Change #4", and go trough.

And, then if you will have any questions, please let me know...

Greetings,
Wilenty

**Comment by Issam-seghir** [comment]
Thanks , restarting my computer fix the problem
