### ISSUE TITLE
Cant install latest nanazip

### ISSUE THREAD

**Issue by Drsexo** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#8]
Last nanazip NanaZipPreview_3.0.756.0 will give an error and refuse to install 
NanaZipPreview_2.1.451.0 works fine
![image](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/101467921/623b098b-6bec-4d8b-8b1a-c7a43222e4b1)

**Comment by Wilenty** [comment]
Hello @Drsexo,
sorry for late response.
Currently I am outside the home in the work, because not so many people willing to support me. So I will fix it in the next version when I will back home (which will be in this or next year).

Greetings,
Wilenty

**Comment by Wilenty** [comment]
Hello @Drsexo,
I had updated 7zTC to v3.0: https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/releases/tag/v3.0

Greetings,
Wilenty
