### ISSUE TITLE
Colorix 4K Icons on 1080p Display

### ISSUE THREAD

**Issue by Aikerin** [Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer#9]
Hello,

I just found the updated fork of this program, and I think it's really neat! One small issue I noticed, though, is that the Colorix 4K icons get really compressed when the folder view is set to small on my 1080p display. This is viewable even in: 
``[Install Directory]\FileType\Colorix 4K``.

![image](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/30785271/f9e2f0c1-0626-4ac3-9f3f-2db26312d671)

I very much like these icons, and the 4K version happens to have almost all icons, whereas the base version was missing a few, so I'm really quite sad. Is there a way for the original Colorix theme to get these missing icons, seeing as the 4K version has more? Again, I absolutely love the FileType theme and would love to have all icons present in the original resolution version!

**Comment by Wilenty** [comment]
Hello @Joenator.

I am not the author of any of the icon packs, I just collected them in one place. 
I made better program to inject/apply them.

You can create your own collection of the icon packs. And you can update missing icons from "Colorix 4K" to "Colorix". Just use some icons manipulate program, for example GIMP, to remove unneeded large icons.

![Large-1](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/61757638/5851df3b-bbc1-42a4-a95e-492289f65144)

BTW, if you find better version of "Colorix" file-type, or you will update missing icons, please share public link to it and I update it in the next version of this program.

Greetings,
Wilenty

**Comment by eqagunn** [comment]
Hi @Joenator. Try the attached. Made it for myself back in 2020. This should display better.
[Colorix_4k_Fixed.zip](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/files/14694059/Colorix_4k_Fixed.zip)

![image](https://github.com/Wilenty/7zTC-7-ZIP-NanaZip-Theme-Changer/assets/25494031/7076c80b-3aa0-484a-989d-39bb3a766898)
